---
output: pdf_document
---

Dear Prof. Michael Kane,

Please find enclosed our resubmission of "brolgar: An R package to BRowse Over Longitudinal Data Graphically and Analytically in R", to consider for publication in the R Journal. This paper is not under consideration for publication elsewhere, but has been submitted to arXiv as a pre-print. We have addressed all feedback from the reviewers, which is detailed point-by-point in the pdf attached to the submission, "response.pdf".

This work provides new tools for exploring longitudinal data in the R package `brolgar`. This R package leverages existing best practices for time series, using the `tsibble` package to encode time series information, as well as extending upon the `ggplot2` package for visualisation. The paper describes getting up and running, sampling intelligently to avoid typical spaghetti plots, how to find interesting individuals, defining individuals based on features, and diagnosing model fits. The methods are illustrated using data on heights across many countries measured over time. 

We have very much enjoyed working on this topic, and have found it very useful in our own analysis of longitudinal data. We hope you find this work, and the paper interesting to the readers of the R Journal.

Kind Regards,

Dr. Nicholas Tierney
Research Software Engineer
Telethon Kids Institute
BPsySc(Hons), PhD (Statistics)
nicholas.tierney@telethonkids.org.au